name: Build

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Build
              run: |
                  CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-w -s" -o pty_windows_amd64.exe
                  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o pty_linux_amd64
                  CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-w -s" -o pty_linux_arm64

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3.1.0
              with:
                  name: pty
                  path: |
                      pty_windows_amd64.exe
                      pty_linux_amd64
                      pty_linux_arm64
